apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-hkat
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ogbj-tenant/rhtap-demo-app/hacbs-test-project-hkat@sha256:be9ba9ec1d4fb29c982a4caf7574f337e251a329630b54f9cf4df3f51af3fb00
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
