apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hkat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hkat
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-hkat
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hkat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hkat
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ogbj-tenant/rhtap-demo-app/hacbs-test-project-hkat@sha256:139c297a795b2320d50343c5a54106d1fae94b528e11fe6afb2b73521156aa8a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
